apiVersion: devops/v1alpha2
kind: Application
group: com.hand.hap-demo
code: hap-demo
name: HAP Demo
version: ${VERSION}
image: registry.saas.hand-china.com/hap/hap-parent:${IMAEG_TAG}
commit: ${COMMIT}

vars:
- name: memory_limits
  description: "内存上限"
  value: "2048Mi"
- name: memory_requests
  description: "内存请求"
  value: "1280Mi"

resources:
- name: demo
  type: mysql
- name: redis
  type: redis

stages:
- name: 初始化配置
  description: '初始化配置信息'
  type: ScriptJob
  config:
    scripts:
    - 'java -jar /usr/local/tomcat/webapps/ROOT/WEB-INF/lib/liquibase-core-3.4.2.jar --driver=com.mysql.jdbc.Driver --classpath=/usr/local/tomcat/webapps/ROOT.war --changeLogFile=com/hand/hap/demo/liquibase.groovy --url=jdbc:mysql://{{ demo.HOST }}:{{ demo.PORT }}/{{ demo.SCHEMA }}  --username={{ demo.USERNAME }} --password={{demo.PASSWORD }} clearCheckSums ;java -Ddb.url=jdbc:mysql://{{ demo.HOST }}:{{ demo.PORT }}/{{ demo.SCHEMA }} -Ddb.user={{ demo.USERNAME }} -Ddb.password={{demo.PASSWORD }} -jar /usr/local/tomcat/webapps/ROOT/WEB-INF/lib/liquibase-core-3.4.2.jar --driver=com.mysql.jdbc.Driver --classpath=/usr/local/tomcat/webapps/ROOT.war --changeLogFile=com/hand/hap/demo/liquibase.groovy --url=jdbc:mysql://{{ demo.HOST }}:{{ demo.PORT }}/{{ demo.SCHEMA }}  --username={{ demo.USERNAME }} --password={{demo.PASSWORD }} update'
- name: 部署
  description: '部署当前服务'
  type: Deploy
  config:
    port: 8080
    env:
    - name: REDIS_IP
      value: "{{ redis.HOST }}"
    - name: REDIS_DB
      value: "{{ redis.SCHEMA }}"
    - name: MYSQL_HOST
      value: "{{ demo.HOST }}"
    - name: MYSQL_DB
      value: "{{ demo.SCHEMA }}"
    - name: MYSQL_USER
      value: "{{demo.USERNAME }}"
    - name: MYSQL_PASS
      value: "{{ demo.PASSWORD }}"
    resources:
      limits:
        memory: "{{ vars.memory_limits }}"
      requests:
        memory: "{{ vars.memory_requests }}"
    readinessProbe:
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
