spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hap_dev?useSSL=false&allowPublicKeyRetrieval=true
    username: hap_dev
    password: hap_dev

redis:
  ip: 127.0.0.1
  db: 10

#db.type property is used for activiti
db:
  type: mysql
  #type: oracle
  #type: mssql
  #type: postgresql

#mybatis.identity property is userd for mybatis Self-increasing primaryKey strategy
mybatis:
  identity: JDBC
  #identity: SEQUENCE

# log config
logging:
  file: hap
  path: log
  level:
    root: debug
  total:  30GB
  history:  30

