apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-config
  labels:
{{ include "service.labels.standard" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 3600
  template:
    metadata:
      name: {{ .Release.Name }}-init-demo
    spec:
      containers:
      - name: {{ .Release.Name }}-init-demo
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - 'java -Xms256M -Xmx512M -Dhap.liquibase=/com/hand/hap/demo/core/demo/liquibase.groovy -Dspring.datasource.url=jdbc:mysql://{{ .Values.env.open.MYSQL_HOST }}:{{ .Values.env.open.MYSQL_PORT }}/{{ .Values.env.open.MYSQL_DB }}  -Dspring.datasource.username={{ .Values.env.open.MYSQL_USER }} -Dspring.datasource.password={{ .Values.env.open.MYSQL_PASS }} -jar hap-demo.jar'
      restartPolicy: Never